apiVersion: apps/v1
kind: Deployment
metadata:
  name: root
  labels:
    app: root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root
  template:
    metadata:
      labels:
        app: root
    spec:
      containers:
        - name: app
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080
              name: http
          resources: { limits: { cpu: 2m, memory: 8Mi } }
---
kind: Service
apiVersion: v1
metadata:
  name: root
spec:
  selector:
    app: root
  ports:
    - port: 80
      targetPort: http
      name: http
