apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-minikube
commonLabels:
  app.kubernetes.io/name: hello-minikube
  app.kubernetes.io/part-of: hello-minikube
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - app-foo.yaml
  - app-bar.yaml
  - app-root.yaml
  - ingress.yaml
